### PR TITLE
adding parallels builder

### PR DESCRIPTION
**Pull request by blairham**

### CODE REVIEW

**Comment by aspring** [comment]
Hi @blairham 

There was Parallels support added previous, however, it looks like the implementation in 0.1.4 was incomplete(a missing require), the rest of the pieces should already be in place.

Ill push a change that fixes that issue, as this PR has a area of changes (ruby version + parellels) so its a much broader scope then a one line fix.

**Comment by blairham** [comment]
sounds good, I could back out the .ruby-version as well.

**Comment by aspring** [comment]
I just pushed the change if you want to give it a test, if all goes well I can get a new gem cut.

**Comment by blairham** [comment]
:+1: 
lgtm

**Pull request closed without merging**
